name: build
on: [push]

jobs:
  # Any checks that run pre-build
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:2.16.1
    steps:
    - uses: actions/checkout@master
    - name: Get Commit or Tag
      id: vars
      run: |
        tag="${GITHUB_SHA:0:8}"
        if [ "${GITHUB_EVENT_NAME}" == "release" ]; then
          ref="${GITHUB_REF}"
          tag=$(echo $GITHUB_REF | sed 's/refs\/tags\///g')
        fi
        echo "::set-output name=tag::$tag"
    - name: Build pdf
      run: |
        apk add make git
        PDF_ENGINE=pdflatex VERSION=$RELEASE_VERSION make build
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
    - name: Provide pdf
      uses: actions/upload-artifact@v2
      with:
        name: proposal.pdf
        path: proposal.pdf
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: proposal.pdf
