name: build
on: [push]

jobs:
  # Any checks that run pre-build
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:2.16.1
    steps:
    - uses: actions/checkout@master
    - name: Build pdf
      run: |
        apk add make git
        PDF_ENGINE=pdflatex make build
    - name: Provide pdf
      uses: actions/upload-artifact@v2
      with:
        name: proposal.pdf
        path: proposal.pdf
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: proposal.pdf
